package model;
// Generated Dec 20, 2017 1:29:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbLoaitintuc generated by hbm2java
 */
public class TbLoaitintuc  implements java.io.Serializable {


     private Integer idloaitin;
     private String tenloai;
     private String mota;
     private Set<TbTintuc> tbTintucs = new HashSet<TbTintuc>(0);

    public TbLoaitintuc() {
    }

	
    public TbLoaitintuc(String tenloai) {
        this.tenloai = tenloai;
    }
    public TbLoaitintuc(String tenloai, String mota, Set<TbTintuc> tbTintucs) {
       this.tenloai = tenloai;
       this.mota = mota;
       this.tbTintucs = tbTintucs;
    }
   
    public Integer getIdloaitin() {
        return this.idloaitin;
    }
    
    public void setIdloaitin(Integer idloaitin) {
        this.idloaitin = idloaitin;
    }
    public String getTenloai() {
        return this.tenloai;
    }
    
    public void setTenloai(String tenloai) {
        this.tenloai = tenloai;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Set<TbTintuc> getTbTintucs() {
        return this.tbTintucs;
    }
    
    public void setTbTintucs(Set<TbTintuc> tbTintucs) {
        this.tbTintucs = tbTintucs;
    }




}


