package model;
// Generated Dec 19, 2017 1:46:37 PM by Hibernate Tools 4.3.1



/**
 * TbPhanhoi generated by hbm2java
 */
public class TbPhanhoi  implements java.io.Serializable {


     private Integer idphanhoi;
     private TbUsers tbUsers;
     private String tieude;
     private String noidung;
     private String email;

    public TbPhanhoi() {
    }

	
    public TbPhanhoi(String tieude, String noidung, String email) {
        this.tieude = tieude;
        this.noidung = noidung;
        this.email = email;
    }
    public TbPhanhoi(TbUsers tbUsers, String tieude, String noidung, String email) {
       this.tbUsers = tbUsers;
       this.tieude = tieude;
       this.noidung = noidung;
       this.email = email;
    }
   
    public Integer getIdphanhoi() {
        return this.idphanhoi;
    }
    
    public void setIdphanhoi(Integer idphanhoi) {
        this.idphanhoi = idphanhoi;
    }
    public TbUsers getTbUsers() {
        return this.tbUsers;
    }
    
    public void setTbUsers(TbUsers tbUsers) {
        this.tbUsers = tbUsers;
    }
    public String getTieude() {
        return this.tieude;
    }
    
    public void setTieude(String tieude) {
        this.tieude = tieude;
    }
    public String getNoidung() {
        return this.noidung;
    }
    
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


