package model;
// Generated Dec 20, 2017 11:02:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbQuyen generated by hbm2java
 */
public class TbQuyen  implements java.io.Serializable {


     private Integer idquyen;
     private String tenquyen;
     private String mota;
     private Set<TbUsers> tbUserses = new HashSet<TbUsers>(0);

    public TbQuyen() {
    }

	
    public TbQuyen(String tenquyen) {
        this.tenquyen = tenquyen;
    }
    public TbQuyen(String tenquyen, String mota, Set<TbUsers> tbUserses) {
       this.tenquyen = tenquyen;
       this.mota = mota;
       this.tbUserses = tbUserses;
    }
   
    public Integer getIdquyen() {
        return this.idquyen;
    }
    
    public void setIdquyen(Integer idquyen) {
        this.idquyen = idquyen;
    }
    public String getTenquyen() {
        return this.tenquyen;
    }
    
    public void setTenquyen(String tenquyen) {
        this.tenquyen = tenquyen;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Set<TbUsers> getTbUserses() {
        return this.tbUserses;
    }
    
    public void setTbUserses(Set<TbUsers> tbUserses) {
        this.tbUserses = tbUserses;
    }




}


