package model;
// Generated Dec 19, 2017 1:46:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbTintuc generated by hbm2java
 */
public class TbTintuc  implements java.io.Serializable {


     private Integer idtintuc;
     private TbLoaitintuc tbLoaitintuc;
     private TbUsers tbUsers;
     private String tentieude;
     private String tomtatnd;
     private String noidung;
     private Date ngaydang;
     private String hinhanh;
     private int luotxem;
     private Set<TbBinhluan> tbBinhluans = new HashSet<TbBinhluan>(0);

    public TbTintuc() {
    }

	
    public TbTintuc(TbLoaitintuc tbLoaitintuc, TbUsers tbUsers, String tentieude, String tomtatnd, String noidung, Date ngaydang, String hinhanh, int luotxem) {
        this.tbLoaitintuc = tbLoaitintuc;
        this.tbUsers = tbUsers;
        this.tentieude = tentieude;
        this.tomtatnd = tomtatnd;
        this.noidung = noidung;
        this.ngaydang = ngaydang;
        this.hinhanh = hinhanh;
        this.luotxem = luotxem;
    }
    public TbTintuc(TbLoaitintuc tbLoaitintuc, TbUsers tbUsers, String tentieude, String tomtatnd, String noidung, Date ngaydang, String hinhanh, int luotxem, Set<TbBinhluan> tbBinhluans) {
       this.tbLoaitintuc = tbLoaitintuc;
       this.tbUsers = tbUsers;
       this.tentieude = tentieude;
       this.tomtatnd = tomtatnd;
       this.noidung = noidung;
       this.ngaydang = ngaydang;
       this.hinhanh = hinhanh;
       this.luotxem = luotxem;
       this.tbBinhluans = tbBinhluans;
    }
   
    public Integer getIdtintuc() {
        return this.idtintuc;
    }
    
    public void setIdtintuc(Integer idtintuc) {
        this.idtintuc = idtintuc;
    }
    public TbLoaitintuc getTbLoaitintuc() {
        return this.tbLoaitintuc;
    }
    
    public void setTbLoaitintuc(TbLoaitintuc tbLoaitintuc) {
        this.tbLoaitintuc = tbLoaitintuc;
    }
    public TbUsers getTbUsers() {
        return this.tbUsers;
    }
    
    public void setTbUsers(TbUsers tbUsers) {
        this.tbUsers = tbUsers;
    }
    public String getTentieude() {
        return this.tentieude;
    }
    
    public void setTentieude(String tentieude) {
        this.tentieude = tentieude;
    }
    public String getTomtatnd() {
        return this.tomtatnd;
    }
    
    public void setTomtatnd(String tomtatnd) {
        this.tomtatnd = tomtatnd;
    }
    public String getNoidung() {
        return this.noidung;
    }
    
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }
    public Date getNgaydang() {
        return this.ngaydang;
    }
    
    public void setNgaydang(Date ngaydang) {
        this.ngaydang = ngaydang;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    public int getLuotxem() {
        return this.luotxem;
    }
    
    public void setLuotxem(int luotxem) {
        this.luotxem = luotxem;
    }
    public Set<TbBinhluan> getTbBinhluans() {
        return this.tbBinhluans;
    }
    
    public void setTbBinhluans(Set<TbBinhluan> tbBinhluans) {
        this.tbBinhluans = tbBinhluans;
    }




}


